### PR TITLE
Tiny fix

### PR DESCRIPTION
**Pull request by Gamecrafter**

### CODE REVIEW

**Comment by MCPEPIG** [comment]
getEvent works too :smile:

**Comment by Gamecrafter** [comment]
Anyways if you submit all these plugins one by one, they'll be rejected for being "too simple". As an experienced developer, I suggest you combine all your plugins that have to do with weapons.

**Comment by MCPEPIG** [comment]
Im not submitting this one.

**Comment by MCPEPIG** [comment]
or the FlameBows one for now.

**Comment by MCPEPIG** [comment]
https://github.com/MCPEPIG/WeaponsPlus

**Pull request closed without merging**
